@host_api = http://localhost:5100
@api_prefix = api/v1

GET {{host_api}}/{{api_prefix}}/

###

PUT {{host_api}}/{{api_prefix}}/http_to_coap/
content-type: application/json

{
    "coap_server" : "192.168.1.37",
    "coap_port" : 5683,
    "coap_method" : "get",
    "coap_payload" : {
        "state": true
    }
}


### 

PUT {{host_api}}/{{api_prefix}}/http_to_coap/
content-type: application/json

{
    "key": "value"
}

### 

PUT {{host_api}}/{{api_prefix}}/http_to_coap/